name: workshop
dependencies:
- python=3.5
- ipython
- jupyter
- matplotlib
- notebook
- ipywidgets
- jupyter_client
- jupyter_core
- numpy>=1.11.0
- pandas>=0.18.1
- patsy
- pip
- readline
- scikit-learn>=0.17.1
- scipy>=0.17.1
- xz=5.0.5
- xlrd