name: workshop
dependencies:
- python=3.5
- ipython
- jupyter
- matplotlib
- notebook
- html5lib
- ipywidgets
- ipyparallel
- jupyter_client
- jupyter_core
- jupyter_nbextensions_configurator
- numpy>=1.11.0
- pandas>=0.18.1
- patsy
- pip
- readline
- seaborn
- scikit-learn>=0.17.1
- scipy>=0.17.1
- sympy
- xz=5.0.5
- xlrd